# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4f7e5e82bf6073209ed0955fa49d8ca2ba275db9e5ffbd3f8ca3641ff19998bc4f21d2493710d6821b02395949af91788686d4db079b2d81ea3e5a9d84b961b

test:
  secret_key_base: 4ae514f5a0f59832994daf50dd43ca97788e572939b85de928af769c315df259dc0575a76b93d547aa2583a2e2a4e5a07131a18477e604a261cc6a6cd2840106

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
